SELECT * FROM(
SELECT
    -- "GOT" AS SOURCE,
    NULLIF(matnr, '') AS matnr,
    NULLIF(werks, '') AS werks,
    NULLIF(meins, '') AS meins,
    NULLIF(waers, '') AS waers,
    NULLIF(bukrs, '') AS bukrs,
    -- NULLIF(pnum1, '') AS pnum1,
    NULLIF(periv, '') AS periv,
    -- NULLIF(datum, DATE '1970-01-01') AS datum,
    -- uzeit,
    -- NULLIF(prmod, '') AS prmod,
    NULLIF(lfgja, '') AS lfgja,
    NULLIF(lfmon, '') AS lfmon,
    NULLIF(bwtar, '') AS bwtar,
    NULLIF(bwkey, '') AS bwkey,
    -- NULLIF(lbkum, 0) AS lbkum,
    -- NULLIF(salk3, 0) AS salk3,
    NULLIF(vprsv, '') AS vprsv,
    NULLIF(verpr, 0) AS verpr,
    NULLIF(stprs, 0) AS stprs,
    NULLIF(peinh, 0) AS peinh,
    NULLIF(bklas, '') AS bklas,
    NULLIF(salkv, 0) AS salkv,
    NULLIF(stprv, 0) AS stprv,
    NULLIF(laepr, DATE '1970-01-01') AS laepr,
    NULLIF(zkprs, 0) AS zkprs,
    NULLIF(zkdat, DATE '1970-01-01') AS zkdat,
    NULLIF(timestamp, 0) AS timestamp,
    NULLIF(pstat, '') AS pstat,
    NULLIF(lvorm, '') AS lvorm,
    NULLIF(bwtty, '') AS bwtty,
    NULLIF(ekgrp, '') AS ekgrp,
    NULLIF(dismm, '') AS dismm,
    NULLIF(perkz, '') AS perkz,
    NULLIF(beskz, '') AS beskz,
    NULLIF(xchar, '') AS xchar,
    NULLIF(mmsta, '') AS mmsta,
    NULLIF(mmstd, DATE '1970-01-01') AS mmstd,
    NULLIF(maabc, '') AS maabc,
    NULLIF(ausme, '') AS ausme,
    NULLIF(dispr, '') AS dispr,
    NULLIF(dispo, '') AS dispo,
    NULLIF(kzdie, '') AS kzdie,
    NULLIF(plifz, 0) AS plifz,
    NULLIF(webaz, 0) AS webaz,
    NULLIF(ausss, 0) AS ausss,
    NULLIF(disls, '') AS disls,
    NULLIF(sobsl, '') AS sobsl,
    NULLIF(minbe, 0) AS minbe,
    NULLIF(eisbe, 0) AS eisbe,
    NULLIF(bstmi, 0) AS bstmi,
    NULLIF(bstma, 0) AS bstma,
    NULLIF(bstfe, 0) AS bstfe,
    NULLIF(bstrf, 0) AS bstrf,
    NULLIF(mabst, 0) AS mabst,
    NULLIF(losfx, 0) AS losfx,
    NULLIF(sbdkz, '') AS sbdkz,
    NULLIF(lagpr, '') AS lagpr,
    NULLIF(altsl, '') AS altsl,
    NULLIF(kzaus, '') AS kzaus,
    NULLIF(ausdt, DATE '1970-01-01') AS ausdt,
    NULLIF(nfmat, '') AS nfmat,
    NULLIF(kzbed, '') AS kzbed,
    NULLIF(miskz, '') AS miskz,
    NULLIF(fhori, '') AS fhori,
    NULLIF(pfrei, '') AS pfrei,
    NULLIF(ffrei, '') AS ffrei,
    NULLIF(rgekz, '') AS rgekz,
    NULLIF(fevor, '') AS fevor,
    NULLIF(bearz, 0) AS bearz,
    NULLIF(ruezt, 0) AS ruezt,
    NULLIF(tranz, 0) AS tranz,
    NULLIF(basmg, 0) AS basmg,
    NULLIF(dzeit, 0) AS dzeit,
    NULLIF(maxlz, 0) AS maxlz,
    NULLIF(lzeih, '') AS lzeih,
    NULLIF(kzpro, '') AS kzpro
FROM sap-iac-test.scct_silver_core.zbw_s_marc_mbew_bq
-- WHERE matnr = "000000000000000003"
-- AND werks = "DC01"
-- matnr = "000000000000000003"
-- AND werks = "DC01"
--
EXCEPT DISTINCT
--
SELECT
    -- "EXPECTED" AS SOURCE,
    NULLIF(matnr, '') AS matnr,
    NULLIF(werks, '') AS werks,
    NULLIF(meins, '') AS meins,
    NULLIF(waers, '') AS waers,
    NULLIF(bukrs, '') AS bukrs,
    -- NULLIF(pnum1, '') AS pnum1,
    NULLIF(periv, '') AS periv,
    -- NULLIF(datum, DATE '1970-01-01') AS datum,
    -- uzeit,
    -- NULLIF(prmod, '') AS prmod,
    NULLIF(lfgja, '') AS lfgja,
    NULLIF(lfmon, '') AS lfmon,
    NULLIF(bwtar, '') AS bwtar,
    NULLIF(bwkey, '') AS bwkey,
    -- NULLIF(lbkum, 0) AS lbkum,
    -- NULLIF(salk3, 0) AS salk3,
    NULLIF(vprsv, '') AS vprsv,
    NULLIF(verpr, 0) AS verpr,
    NULLIF(stprs, 0) AS stprs,
    NULLIF(peinh, 0) AS peinh,
    NULLIF(bklas, '') AS bklas,
    NULLIF(salkv, 0) AS salkv,
    NULLIF(stprv, 0) AS stprv,
    NULLIF(laepr, DATE '1970-01-01') AS laepr,
    NULLIF(zkprs, 0) AS zkprs,
    NULLIF(zkdat, DATE '1970-01-01') AS zkdat,
    NULLIF(timestamp, 0) AS timestamp,
    NULLIF(pstat, '') AS pstat,
    NULLIF(lvorm, '') AS lvorm,
    NULLIF(bwtty, '') AS bwtty,
    NULLIF(ekgrp, '') AS ekgrp,
    NULLIF(dismm, '') AS dismm,
    NULLIF(perkz, '') AS perkz,
    NULLIF(beskz, '') AS beskz,
    NULLIF(xchar, '') AS xchar,
    NULLIF(mmsta, '') AS mmsta,
    NULLIF(mmstd, DATE '1970-01-01') AS mmstd,
    NULLIF(maabc, '') AS maabc,
    NULLIF(ausme, '') AS ausme,
    NULLIF(dispr, '') AS dispr,
    NULLIF(dispo, '') AS dispo,
    NULLIF(kzdie, '') AS kzdie,
    NULLIF(plifz, 0) AS plifz,
    NULLIF(webaz, 0) AS webaz,
    NULLIF(ausss, 0) AS ausss,
    NULLIF(disls, '') AS disls,
    NULLIF(sobsl, '') AS sobsl,
    NULLIF(minbe, 0) AS minbe,
    NULLIF(eisbe, 0) AS eisbe,
    NULLIF(bstmi, 0) AS bstmi,
    NULLIF(bstma, 0) AS bstma,
    NULLIF(bstfe, 0) AS bstfe,
    NULLIF(bstrf, 0) AS bstrf,
    NULLIF(mabst, 0) AS mabst,
    NULLIF(losfx, 0) AS losfx,
    NULLIF(sbdkz, '') AS sbdkz,
    NULLIF(lagpr, '') AS lagpr,
    NULLIF(altsl, '') AS altsl,
    NULLIF(kzaus, '') AS kzaus,
    NULLIF(ausdt, DATE '1970-01-01') AS ausdt,
    NULLIF(nfmat, '') AS nfmat,
    NULLIF(kzbed, '') AS kzbed,
    NULLIF(miskz, '') AS miskz,
    NULLIF(fhori, '') AS fhori,
    NULLIF(pfrei, '') AS pfrei,
    NULLIF(ffrei, '') AS ffrei,
    NULLIF(rgekz, '') AS rgekz,
    NULLIF(fevor, '') AS fevor,
    NULLIF(bearz, 0) AS bearz,
    NULLIF(ruezt, 0) AS ruezt,
    NULLIF(tranz, 0) AS tranz,
    NULLIF(basmg, 0) AS basmg,
    NULLIF(dzeit, 0) AS dzeit,
    NULLIF(maxlz, 0) AS maxlz,
    NULLIF(lzeih, '') AS lzeih,
    NULLIF(kzpro, '') AS kzpro
FROM sap-iac-test.scct_bronze_sap.zbw_s_marc_mbew bronze
WHERE
EXISTS (
    SELECT matnr, werks FROM `sap-iac-test.GS4_CDC_PS.mbew` cdc_raw WHERE
    bronze.matnr = cdc_raw.matnr AND bronze.werks = cdc_raw.bwkey
)
)
ORDER BY
matnr, werks
;